# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class PokemonSlowdown < Formula
  desc "A calm, keyboard-first terminal client for Pokémon Showdown"
  homepage "https://github.com/unnipv/pokemon-slowdown"
  version "0.2.2"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/unnipv/pokemon-slowdown/releases/download/v0.2.2/pokemon-slowdown_0.2.2_darwin_amd64.tar.gz"
      sha256 "d7cf1839357b4fff9f622939d891e9d5a969fb77a1f31cc554298fb6a09b4e52"

      define_method(:install) do
        bin.install "slowdown"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/unnipv/pokemon-slowdown/releases/download/v0.2.2/pokemon-slowdown_0.2.2_darwin_arm64.tar.gz"
      sha256 "9ed8be72d80b95db2e859f5d37f86d03a02d20a1ac0a3d0110927b93b4538e8c"

      define_method(:install) do
        bin.install "slowdown"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/unnipv/pokemon-slowdown/releases/download/v0.2.2/pokemon-slowdown_0.2.2_linux_amd64.tar.gz"
      sha256 "2462872678fffc62d5a741acbd85e6a7dc4e9d983e12ce64925fa15c8ccbd47d"
      define_method(:install) do
        bin.install "slowdown"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/unnipv/pokemon-slowdown/releases/download/v0.2.2/pokemon-slowdown_0.2.2_linux_arm64.tar.gz"
      sha256 "e78bf1150d1be95b8a83b9cc3f7f197eb2a3c40b0ec55e2c6f70409e55f93a61"
      define_method(:install) do
        bin.install "slowdown"
      end
    end
  end

  test do
    system "#{bin}/slowdown", "--version"
  end
end
