# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class PokemonSlowdown < Formula
  desc "A calm, keyboard-first terminal client for Pokémon Showdown"
  homepage "https://github.com/unnipv/pokemon-slowdown"
  version "0.2.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/unnipv/pokemon-slowdown/releases/download/v0.2.1/pokemon-slowdown_0.2.1_darwin_amd64.tar.gz"
      sha256 "2cf4cb7d5f9981a356bfbd362ccf9b490fe59995f5f45e6e034ff7b8a3eb7dd2"

      define_method(:install) do
        bin.install "slowdown"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/unnipv/pokemon-slowdown/releases/download/v0.2.1/pokemon-slowdown_0.2.1_darwin_arm64.tar.gz"
      sha256 "5351e528b0e61cd1a25cb669c6d0fc7f3e6674d54f0bde946ac50a721044a668"

      define_method(:install) do
        bin.install "slowdown"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/unnipv/pokemon-slowdown/releases/download/v0.2.1/pokemon-slowdown_0.2.1_linux_amd64.tar.gz"
      sha256 "1a104955a7636e7ef9c01ffdb7c9478577a4aba219efc1b57ceb8b8e3830c320"
      define_method(:install) do
        bin.install "slowdown"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/unnipv/pokemon-slowdown/releases/download/v0.2.1/pokemon-slowdown_0.2.1_linux_arm64.tar.gz"
      sha256 "a3f7fe5cae711cb7d74d9b078f1d383b40824e2e8365a3ee96ae3957176955b5"
      define_method(:install) do
        bin.install "slowdown"
      end
    end
  end

  test do
    system "#{bin}/slowdown", "--version"
  end
end
