# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class PokemonSlowdown < Formula
  desc "A calm, keyboard-first terminal client for Pokémon Showdown"
  homepage "https://github.com/unnipv/pokemon-slowdown"
  version "0.3.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/unnipv/pokemon-slowdown/releases/download/v0.3.0/pokemon-slowdown_0.3.0_darwin_amd64.tar.gz"
      sha256 "271074782e9ceb8e75f4b6a0a6cd0df517f323b6b2bbe2ee55433f8821a10634"

      define_method(:install) do
        bin.install "slowdown"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/unnipv/pokemon-slowdown/releases/download/v0.3.0/pokemon-slowdown_0.3.0_darwin_arm64.tar.gz"
      sha256 "42a3eb40110c80f1392f0aae5dd586b689b4372fe9ad7d2e6fd99408acd2c815"

      define_method(:install) do
        bin.install "slowdown"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/unnipv/pokemon-slowdown/releases/download/v0.3.0/pokemon-slowdown_0.3.0_linux_amd64.tar.gz"
      sha256 "db209106b45b5d25c355bd3264c701c57e39f67b0905e2afd08fc76d779bd714"
      define_method(:install) do
        bin.install "slowdown"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/unnipv/pokemon-slowdown/releases/download/v0.3.0/pokemon-slowdown_0.3.0_linux_arm64.tar.gz"
      sha256 "8fd21444f05e09736f23f4175daffb98238af2c66f80ccd77b415e23effef043"
      define_method(:install) do
        bin.install "slowdown"
      end
    end
  end

  test do
    system "#{bin}/slowdown", "--version"
  end
end
